version: 2
# Jobs: see https://circleci.com/docs/2.0/jobs-steps/
jobs:
  test:
    docker:
      - image: circleci/python:2.7-buster
    environment:
      COMPOSE_FILE: .circleci/docker-compose.circle.yml
      COMPOSE_PROJECT_NAME: redash
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run docker-compose
          command: docker-compose up -d && sleep 5
      - run:
          name: Create database
          command: docker-compose run --rm postgres psql -U postgres -h postgres -c "create database tests;" || echo "Error while creating tests database"
      - run:
          name: Run Tests
          command: docker-compose run --rm `bash <(curl -s https://codecov.io/env)` server ci

  # Runs when the repository is tagged for release; see the workflows section
  # below for trigger logic.
  deploy:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install deployment tools
          command: |
            pip install --pre --upgrade setuptools wheel twine
      - run:
          name: Create the distribution files
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Check Readme rendering
          command: |
            twine check dist/*
      - run:
          name: Upload to PyPI
          command: |
            twine upload -u "${TWINE_USERNAME}" -p "${TWINE_PASSWORD}" --disable-progress-bar dist/*

# Workflows: see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /[0-9]{4}.[0-9]{1,2}.[0-9]+/  # Calver: YY.M.PATCH
            branches:
              # Ignore all branches; this workflow should only run for tags.
              ignore: /.*/
